### ISSUE TITLE
Connection to PowerPDU 8QS periodically timesout

### ISSUE THREAD

**Issue by hugo-di** [netioproducts/PyNetio#11]
I am using the PyNetio package and a Raspberry Pi to control the PowerPDU 8QS. The Raspberry Pi is connected directly to the PowerPDU via LAN. I have noticed that the LAN connection to the 8QS periodically times out every few hours. Due to the number of requests being handled by the 8QS between timeouts its on-board log does go far back enough to view events that occurred around this time. 

Below is the traceback from the timeout:

`HTTPConnectionPool(host='192.168.1.78', port=80): Max retries exceeded with url: /netio.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaedf0460>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xaedf0460>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.78', port=80): Max retries exceeded with url: /netio.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaedf0460>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Desktop/<REDACTED>/<REDACTED>/drivers/netio_driver.py", line 124, in disable_outlet
    self.n.set_output(outlet.value, self.OUTLET_OFF)
  File "/usr/local/lib/python3.9/dist-packages/Netio/Device.py", line 85, in set_output
    self.set_outputs({id: action})
  File "/usr/local/lib/python3.9/dist-packages/Netio/Device.py", line 80, in set_outputs
    self._set_outputs(actions)
  File "/usr/local/lib/python3.9/dist-packages/Netio/Device.py", line 205, in _set_outputs
    return self._post(body)
  File "/usr/local/lib/python3.9/dist-packages/Netio/Device.py", line 152, in _post
    response = requests.post(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.78', port=80): Max retries exceeded with url: /netio.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaedf0460>: Failed to establish a new connection: [Errno 110] Connection timed out'))
`

**Comment by AdamVerner** [comment]
Hello,
This does not seem like an issue with the package. You might benefit from more robust retry logic (you can use [stamina](https://pypi.org/project/stamina/) for example).
Closing this as stale.

Cheers
